# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromxp', models.FloatField()),
                ('fromyp', models.FloatField()),
                ('targetxp', models.FloatField()),
                ('targetyp', models.FloatField()),
                ('type', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
